config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3api:
      branch: hackathon
      repo: https://git.scc.kit.edu/synergy.o3as/o3api/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-red-saola.sh
        container: qc.acc_paltry-sapphire-stoat
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-seashell-kakapo.sh
        container: qc.doc_gamy-magnolia-badger
      git.scc.kit.edu/synergy.o3as/o3api git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-ruby-starfish.sh
        container: qc.doc_stealthy-russet-kangaroo
      git.scc.kit.edu/synergy.o3as/o3api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-flounder.sh
        container: qc.doc_messy-seashell-robin
      git.scc.kit.edu/synergy.o3as/o3api restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ultramarine-lizard.sh
        container: qc.doc_whiny-azure-bonobo
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-burgundy-crocodile.sh
        container: qc.lic_chewy-cerulean-crocodile
  QC.Sec:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-ochre-elephant.sh
        container: qc.sec_skimpy-alizarin-yak
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-indigo-blue.sh
        container: qc.sty_cranky-amaranth-orangutan
      git.scc.kit.edu/synergy.o3as/o3api hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-peach-akbash.sh
        container: qc.sty_lovely-seashell-cougar
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-platinum-wrasse.sh
        container: qc.ver_squeaky-teal-jackal
timeout: 1800
