config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: sqa
      repo: https://github.com/EOSC-synergy/saps-catalog/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-buff-buzzard.sh
        container: qc.acc_crappy-turquoise-butterfly
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-malachite-tzu.sh
        container: qc.doc_jumpy-linen-crocodile
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-buff-raccoon.sh
        container: qc.doc_pretty-chestnut-eel
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ruby-quail.sh
        container: qc.doc_stinky-cerulean-dhole
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-periwinkle-sloth.sh
        container: qc.lic_bluesy-crimson-spoonbill
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-ruby-impala.sh
        container: qc.ver_goopy-ochre-stingray
timeout: 1800
