config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/saps-catalog:
      branch: develop
      repo: https://github.com/EOSC-synergy/saps-catalog/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-amethyst-horse.sh
        container: qc.acc_cranky-sepia-barb
  QC.Doc:
    repos:
      github.com/EOSC-synergy/saps-catalog find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-lavender-seal.sh
        container: qc.doc_squirrely-ochre-mongoose
      github.com/EOSC-synergy/saps-catalog git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-ochre-gopher.sh
        container: qc.doc_droopy-champagne-pinscher
      github.com/EOSC-synergy/saps-catalog markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-smalt-dane.sh
        container: qc.doc_wiggy-silver-ferret
  QC.Lic:
    repos:
      github.com/EOSC-synergy/saps-catalog licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ruby-hornet.sh
        container: qc.lic_beady-tomato-wildebeest
  QC.Sec:
    repos:
      github.com/EOSC-synergy/saps-catalog bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-yellow-schnauzer.sh
        container: qc.sec_squirrely-seashell-kiwi
  QC.Sty:
    repos:
      github.com/EOSC-synergy/saps-catalog flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-asparagus-cassowary.sh
        container: qc.sty_boozy-razzmatazz-snake
  QC.Ver:
    repos:
      github.com/EOSC-synergy/saps-catalog get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-chocolate-flamingo.sh
        container: qc.ver_stealthy-periwinkle-warthog
timeout: 1800
