config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/oscar:
      branch: master
      repo: https://github.com/grycap/oscar/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-peach-goat.sh
        container: qc.acc_squirrely-cornflower-emu
  QC.Doc:
    repos:
      github.com/grycap/oscar find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-silver-squirt.sh
        container: qc.doc_scummy-apricot-birman
      github.com/grycap/oscar git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-cinnamon-axolotl.sh
        container: qc.doc_scaly-periwinkle-kiwi
      github.com/grycap/oscar markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-peach-cockroach.sh
        container: qc.doc_beady-periwinkle-lemur
  QC.Lic:
    repos:
      github.com/grycap/oscar licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-pumpkin-capybara.sh
        container: qc.lic_bluesy-lavender-squid
  QC.Sec:
    repos:
      github.com/grycap/oscar bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-emerald-camel.sh
        container: qc.sec_messy-sapphire-orangutan
  QC.Sty:
    repos:
      github.com/grycap/oscar flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-orchid-squirt.sh
        container: qc.sty_craggy-tomato-spaniel
  QC.Ver:
    repos:
      github.com/grycap/oscar get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-heliotrope-dalmatian.sh
        container: qc.ver_crappy-alizarin-bombay
timeout: 1800
