config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/onedataSim:
      branch: dev
      repo: https://github.com/EOSC-synergy/onedataSim/
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/onedataSim git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ecru-tarantula.sh
        container: qc.acc_stuffy-bistre-macaque
  QC.Doc:
    repos:
      github.com/EOSC-synergy/onedataSim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-gold-chinchilla.sh
        container: qc.doc_pretty-scarlet-woodpecker
      github.com/EOSC-synergy/onedataSim git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-blue-leopard.sh
        container: qc.doc_ready-wheat-terrier
      github.com/EOSC-synergy/onedataSim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-brass-dhole.sh
        container: qc.doc_breezy-ruby-mau
  QC.Lic:
    repos:
      github.com/EOSC-synergy/onedataSim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-orange-peccary.sh
        container: qc.lic_frumpy-malachite-wolfhound
  QC.Sec:
    repos:
      github.com/EOSC-synergy/onedataSim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cardinal-blue.sh
        container: qc.sec_muggy-goldenrod-hyrax
  QC.Sty:
    repos:
      github.com/EOSC-synergy/onedataSim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-pink-wombat.sh
        container: qc.sty_silly-sapphire-jaguar
      github.com/EOSC-synergy/onedataSim hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-rust-dugong.sh
        container: qc.sty_grumpy-gold-cockroach
      github.com/EOSC-synergy/onedataSim jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-buff-chicken.sh
        container: qc.sty_trippy-thistle-squirrel
  QC.Ver:
    repos:
      github.com/EOSC-synergy/onedataSim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-tan-octopus.sh
        container: qc.ver_skimpy-teal-mastiff
timeout: 1800
