config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/tdviet4free/fedcloudclient:
      branch: sqaaas-test
      repo: https://github.com/tdviet4free/fedcloudclient/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/tdviet4free/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-pink-kakapo.sh
        container: qc.acc_lousy-platinum-akita
  QC.Doc:
    repos:
      github.com/tdviet4free/fedcloudclient find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-auburn-mist.sh
        container: qc.doc_grumpy-sapphire-ant
      github.com/tdviet4free/fedcloudclient git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-yellow-mayfly.sh
        container: qc.doc_sunny-cornflower-mandrill
      github.com/tdviet4free/fedcloudclient markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-white-dog.sh
        container: qc.doc_leaky-silver-armadillo
      github.com/tdviet4free/fedcloudclient restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-puce-fowl.sh
        container: qc.doc_beady-rust-mandrill
  QC.Lic:
    repos:
      github.com/tdviet4free/fedcloudclient licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cinnamon-foxhound.sh
        container: qc.lic_sleazy-taupe-dragonfly
  QC.Sec:
    repos:
      github.com/tdviet4free/fedcloudclient bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-scarlet-liger.sh
        container: qc.sec_sunny-burgundy-hamster
  QC.Sty:
    repos:
      github.com/tdviet4free/fedcloudclient flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-scarlet-ragdoll.sh
        container: qc.sty_pokey-orange-leopard
      github.com/tdviet4free/fedcloudclient hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-firebrick-mist.sh
        container: qc.sty_gamy-lilac-dog
      github.com/tdviet4free/fedcloudclient jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cardinal-dalmatian.sh
        container: qc.sty_skimpy-wisteria-cockroach
  QC.Ver:
    repos:
      github.com/tdviet4free/fedcloudclient get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-corn-mule.sh
        container: qc.ver_bluesy-cardinal-rottweiler
timeout: 1800
